### ISSUE TITLE
Implement ByteOrder to allow reading/writing primitive values

### ISSUE THREAD

**Issue by natemara** [rust-embedded/rust-i2cdev#12]
Trait documentation is here: http://burntsushi.net/rustdoc/byteorder/trait.ByteOrder.html

Not sure how much minimalism you're going for with this crate, but it seems like it would be useful to be able to read/write arbitrary primitive types to devices. It seems like that the core struct [used to](https://github.com/posborne/rust-i2cdev/blob/a22f4c7bc7d6f49b6d6e0f71639a677e0b8e5437/src/core.rs) implement the `io::Read` trait which would have automatically derived the necessary functions. Is there some reason that this was removed, and would you be opposed to a default implementation of the read/write methods in the main trait?

**Comment by posborne** [comment]
The impl of `io::Read` was removed as part of the changes to move closer to a place where `I2CDevice` could be used in `no_std` environments.  It isn't there at this point, but has moved there.  I think adding back an impl is reasonable if left out of core (maybe an `ext` module or something).  It should be possible to implement it pretty generically for against the trait itself (you'll need to map from `I2CError` to `io::Error` and such but `read`/`write` are present).

Right now, the use of the `byteorder` crate is an implementation detail and not something I am looking to further couple to.  In my mind, the concern of reading/writing to I2C devices is separate from that of properly packing/parsing data buffers.  There are plenty of other creates out there for doing that (with byteorder on the simple end and more complex things like nom on the high end).
