### ISSUE TITLE
i2cdev recompiles every time

### ISSUE THREAD

**Issue by querry43** [rust-embedded/rust-i2cdev#37]
i2cdev compiles every time I `cargo build`.  It doesn't appear to be a problem in `0.3.1`.

```
$ cargo build
   Compiling i2c-pca9685 v0.1.9-pre (https://github.com/querry43/i2c-pca9685#4b0ddf24)
   Compiling i2cdev v0.3.2
   Compiling assigato-remote v0.1.0 (file:///home/matt/work/assigato-remote)
    Finished dev [unoptimized + debuginfo] target(s) in 13.9 secs
$ cargo build
   Compiling i2cdev v0.3.2
   Compiling i2c-pca9685 v0.1.9-pre (https://github.com/querry43/i2c-pca9685#4b0ddf24)
   Compiling assigato-remote v0.1.0 (file:///home/matt/work/assigato-remote)
    Finished dev [unoptimized + debuginfo] target(s) in 11.87 secs
```

```
[dependencies]
i2cdev = "0.3.2"
```
`rustc 1.24.0 (4d90ac38c 2018-02-12)`

**Comment by nastevens** [comment]
Looks like this is a [known issue of the `skeptic` crate](https://github.com/budziq/rust-skeptic/issues/25) that was [fixed after the 0.13.2 release](https://github.com/budziq/rust-skeptic/pull/68). I confirmed that if I add the following to my project's `Cargo.toml` the issue goes away:

```toml
[replace]
"skeptic:0.13.2" = { git = 'https://github.com/budziq/rust-skeptic' }
```

@querry43 could you please also verify that this addresses the issue in your case?

Obviously the long-term solution is for a new release of `skeptic` with the fix - I have opened an issue requesting the author to push a new release: https://github.com/budziq/rust-skeptic/issues/75

**Comment by querry43** [comment]
Oh yea, that works great.  Thanks for finding that.  It fixes a problem I have with another crate too.

**Comment by nastevens** [comment]
Upstream release of rust-skeptic is done: https://github.com/budziq/rust-skeptic/issues/75

Since rust-i2cdev is used as a library, if you have an application with a `Cargo.lock` you can do `cargo update -p skeptic` to get the bumped version. I tested it out locally and i2cdev is no longer rebuilding every time `cargo build` is run.

**Comment by querry43** [comment]
Yea, I saw the upstream commit.  Thanks.
