### ISSUE TITLE
Incorrect smbus methods

### ISSUE THREAD

**Issue by arcnmx** [rust-embedded/rust-i2cdev#38]
Currently `LinuxI2CDevice::smbus_process_block` calls `ffi::i2c_smbus_write_i2c_block_data` instead of the real smbus2 ffi method (which doesn't seem to be implemented in `ffi.rs`), and `LinuxI2CDevice::smbus_write_i2c_block_data` doesn't exist as one would expect it to.

`smbus_process_block` presumably needs to be renamed to `smbus_write_i2c_block_data`, and `LinuxI2CDevice::smbus_process_block` added with the proper signature (returning a vec) plus `i2c_smbus_process_call_block` or similar added to the ffi for it to use.

**Comment by posborne** [comment]
Thanks for filing the issue @arcnmx, would you be willing to put together a PR for this?  I think what you have proposed seems reasonable.
