### ISSUE TITLE
Large dependency tree

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/rust-i2cdev#41]
I'm using this crate on a Raspberry Pi as part of my Sense HAT driver. Unfortunately it takes about 5 minutes to build (on the fastest Pi 3B+), and that seems a lot for just reading and writing some bytes from /dev/i2c. From the tree it looks like `skeptic` is pulling in most of it - is this crate strictly required, and/or is there any chance it could be placed behind a feature flag? Thanks!

**Comment by ryankurte** [comment]
#47 should have resolved this, is it possible to make a release so we can bump https://github.com/rust-embedded/linux-embedded-hal?

**Comment by posborne** [comment]
@ryankurte Yep, I'll cut 0.4.1

**Comment by posborne** [comment]
0.4.1 is now published to crates.
