### ISSUE TITLE
Missing docs on I2CMessage

### ISSUE THREAD

**Issue by Zalastra** [rust-embedded/rust-i2cdev#57]
The implementation block defining `fn with_address(..)` and `fn with_flags(..)` does not show up in the docs. Presumably because it's an impl on a type alias of a private struct?

**Comment by eldruin** [comment]
The docs are just missing. I am working on a PR for this.

**Comment by Zalastra** [comment]
Well yes the actual documentation is missing but undocumented items are normally still listed in the doc pages. This implementation block is straight up not showing up. See: https://docs.rs/i2cdev/0.4.4/i2cdev/linux/type.LinuxI2CMessage.html

Even if adding any documentation to these items does not change this.
