### ISSUE TITLE
Examples in README are not correct any more

### ISSUE THREAD

**Issue by posborne** [rust-embedded/rust-i2cdev#9]

**Comment by rundrop1** [comment]
Hello, are you accepting PR's for examples?  Or even additions to /sensors?  I know you are planning on incorporating zinc/zinc like structure are you planning on deprecating LinuxI2CDevice?

**Comment by posborne** [comment]
Hello @rundrop1.  PRs for both examples and new sensors would be great!

There are no plans to deprecate LinuxI2CDevice.  With the recent changes, it is now possible for sensors to be written that only depend on the I2CDevice trait and not on the linux one directly.  As long as you follow the style of the other sensors, things should work out well.  The new design also allows for unit testing.

**Comment by rundrop1** [comment]
Awesome! Very stoked to push a request, am trying to get it up tonight!

**Comment by posborne** [comment]
Hi @rundrop1, I know it has been a very long time.  Did you ever end up putting together any changes for this or other parts of the library?  Did the crate work for your use cases?

**Comment by rundrop1** [comment]
The lib works wonderfully! I didn't need to make any changes.  Very excited to see Rust moving to more embedded stuffs!  At some point I'll clean up my PCA9685 driver but I'm in the middle of something else at the moment!

Thanks for all the work you've done on the lib.
